apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "perftest"
      sequences:
        - name: "scale-and-test"
          tasks:
            - name: "scale-up"        
            - name: "test"
            - name: "evaluation"
            - name: "scale-down"
        - name: "rollback"
          triggeredOn: 
          - event: "perftest.scale-and-test.finished"
            selector:
              match: 
                result: "fail"
          tasks:
            - name: "scale-down"
        - name: "no-rollback-since-pass"
          triggeredOn:
          - event: perftest.scale-and-test.finished
          tasks:
            - name : "notify"
     